package Parser_RPAL;

public enum Node_Type {
    LET, IN, LAMBDA, WHERE, TAU, AUG, CONDITIONAL, Bool_OR, Bool_AND, Bool_NOT, GR, GE, LS, LE, EQ, NE, PLUS, MINUS,
    NEG, MUL, DIVISION, POWER, AT, GAMMA, T_TRUE, T_FALSE, NIL, DUMMY, WITHIN, AND, REC, EQUAL, FCN_FORM,
    LEFT_PAREN, RIGHT_PAREN, PARENTHESIS, SEMICOLON, COMMA,
    FN, DOT, STRAIGHT_BAR, IDENTIFIER, INTEGER, STRING, YSTAR

}
